import os

AWS_COGNITO_USER_POOL = os.getenv('AWS_COGNITO_USER_POOL')
AWS_COGNITO_CLIENT_ID = os.getenv('AWS_COGNITO_CLIENT_ID')
AWS_COGNITO_REGION = os.getenv('AWS_COGNITO_REGION')
WSS_ENDPOINT = os.getenv('WSS_ENDPOINT')

